name: scala test
on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checking code formatting
        run: sbt formatCheck scalafixAll
  main:
    name: scala-simple-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 2.12.13
          - 2.13.5
        project:
          - playJsonProject
          - circeProject
          - upickleProject
          - json4sCommonProject
          - json4sJacksonProject
          - sprayJsonProject
          - argonautProject
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: scala ${{ matrix.project }} ${{ matrix.scala }}
        env:
          CMD: ${{ matrix.cmd }}
        run: |
          sbt ++${{ matrix.scala }} ${{ matrix.project }}/test
